ATTACK_DATA = {
    'scratch':    {'target': 'opponent', 'amount': 0.8,  'cost': 0, 'keyword': None,
                   'element': 'normal',  'animation': 'scratch',     'movesets': 'attack',
                   'buff': None,		 'debuff': None,
                   'detail1': 'Deal',
                   'detail2': 'of ATK.',},
    
	'block':      {'target': 'self',     'amount': 0,    'cost': 0, 'keyword': 'block',
                   'element': 'normal',  'animation': 'fire',       'movesets': 'attack',
                   'buff': None,		 'debuff': None,
                   'detail1': 'Blocking for',
                   'detail2': 'turn(s).',},

	'burn':       {'target': 'opponent', 'amount': 2,    'cost': 15, 'keyword': None,
                   'element': 'fire',    'animation': 'fire',       'movesets': 'attack',
                   'buff': None,		 'debuff': None,
                   'detail1': 'Deal',
                   'detail2': 'of ATK.',},
	'heal':       {'target': 'player',   'amount': -1.2, 'cost': 15, 'keyword': 'heal',
                   'element': 'normal',  'animation': 'green',      'movesets': 'attack',
                   'buff': None,		 'debuff': None,
                   'detail1': 'Deal',
                   'detail2': 'of ATK.',},
	'battlecry':  {'target': 'player',   'amount': 1.4,  'cost': 20, 'keyword': None,
                   'element': 'normal',  'animation': 'green',      'movesets': 'attack',
                   'buff': None,		 'debuff': None,
                   'detail1': 'Deal',
                   'detail2': 'of ATK.',},
	'spark':      {'target': 'opponent', 'amount': 1.1,  'cost': 20, 'keyword': None,
                   'element': 'fire',    'animation': 'fire',       'movesets': 'attack',
                   'buff': None,		 'debuff': None,
                   'detail1': 'Deal',
                   'detail2': 'of ATK.',},
	'splash':     {'target': 'opponent', 'amount': 1.1,    'cost': 15, 'keyword': None,
                   'element': 'water',   'animation': 'splash',     'movesets': 'attack',
                   'buff': None,		 'debuff': None,
                   'detail1': 'Deal',
                   'detail2': 'of ATK.',},
	'fire':       {'target': 'opponent', 'amount': 2,    'cost': 15, 'keyword': None,
                   'element': 'fire',    'animation': 'fire',       'movesets': 'attack',
                   'buff': None,		 'debuff': None,
                   'detail1': 'Deal',
                   'detail2': 'of ATK.',},
	'explosion':  {'target': 'opponent', 'amount': 1.7,    'cost': 90, 'keyword': None,
                   'element': 'fire',    'animation': 'explosion',  'movesets': 'attack',
                   'buff': None,		 'debuff': None,
                   'detail1': 'Deal',
                   'detail2': 'of ATK.',},
	'annihilate': {'target': 'opponent', 'amount': 2,    'cost': 15, 'keyword': None,
                   'element': 'fire',    'animation': 'explosion',  'movesets': 'attack',
                   'buff': None,		 'debuff': None,
                   'detail1': 'Deal',
                   'detail2': 'of ATK.',},
	'ice':        {'target': 'opponent', 'amount': 1.3,    'cost': 15, 'keyword': None,
                   'element': 'water',   'animation': 'ice',        'movesets': 'attack',
                   'buff': None,		 'debuff': None,
                   'detail1': 'Deal',
                   'detail2': 'of ATK.',},
    'ice spike':  {'target': 'opponent', 'amount': 2,    'cost': 15, 'keyword': None,
                   'element': 'water',   'animation': 'ice',        'movesets': 'attack',
                   'buff': None,		 'debuff': None,
                   'detail1': 'Deal',
                   'detail2': 'of ATK.',},
    'death ray':  {'target': 'opponent', 'amount': 34,    'cost': 1500, 'keyword': None,
                   'element': 'normal',   'animation': 'explosion',  'movesets': 'attack',
                   'buff': None,		 'debuff': None,
                   'detail1': 'Deal',
                   'detail2': 'of ATK.',},
}
